_extends: .github
repository:
  name: awesome-multipart-parsing
  description: list to keep track of node.js multipart parsing libs
  homepage: 'https://github.com/trevtrich/awesome-multipart-parsing#readme'
  private: false
